### ISSUE TITLE
Ruler should start goroutines in its constructor

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#238]
See https://github.com/weaveworks/cortex/blob/master/cmd/ruler/main.go#L44

And https://github.com/weaveworks/cortex/pull/237#discussion_r97648867

We're settling on this as the common pattern.

**Comment by jml** [comment]
I posted a PR to do this (#239), and I'm more-or-less happy with it being merged.

I object slightly to the "we" part, or at least want to emphasise the "settling" part. I think leaving concurrency up to callers is the right thing to do, and haven't been persuaded otherwise. I just don't think starting the goroutine in the constructor is that much worse, and think consistency is important.
