### ISSUE TITLE
Lines shouldn't be able to go backwards...

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#244]
<img width="912" alt="screen shot 2017-01-26 at 21 32 07" src="https://cloud.githubusercontent.com/assets/444037/22365965/3015de38-e472-11e6-8c5d-1ae712be6996.png">

**Comment by juliusv** [comment]
I can't reproduce this, which is partially due to not being able to chose a time range in the current Cortex UI (cc @davkal). I first suspected this was due to not setting the `linear` interpolation option in Rickshaw (we had this problem in Prometheus once), but this option is set correctly: https://github.com/weaveworks/service-ui/blob/61516a01b2199b2f493bb9582b0515e1dd328542/client/src/pages/prom/graph/prom-graph-component.jsx#L137

**Comment by tomwilkie** [comment]
I have the exact repo still open, so I can get the results from the server.

Will do tomorrow.

**Comment by davkal** [comment]
Seen this again?

**Comment by tomwilkie** [comment]
Yes:

<img width="905" alt="screen shot 2017-02-07 at 14 58 03" src="https://cloud.githubusercontent.com/assets/444037/22696442/ed69e408-ed45-11e6-9a1d-401701e60fee.png">

Here's the data https://gist.github.com/tomwilkie/609966c11878d1a84fc1787088962f6c

**Comment by juliusv** [comment]
I couldn't find any out-of-order samples in the dataset. So it seems to be some strange visual glitch which even happens when all samples are sorted correctly.

**Comment by juliusv** [comment]
@davkal fixed this in https://github.com/weaveworks/service-ui/commit/638485adcbb191f076e8bdab7d67693aa41252f7
