### ISSUE TITLE
incorrect query result compared to stock prometheus

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#358]
Dev cortex, looking at prod:
![screenshot_2017-03-19_08-32-14](https://cloud.githubusercontent.com/assets/109109/24079396/ee660c58-0c7e-11e7-9f40-b4f7b8d5771c.png)
Prometheus in prod:
![screenshot_2017-03-19_08-33-21](https://cloud.githubusercontent.com/assets/109109/24079398/f78d9058-0c7e-11e7-8d2b-c008698f2220.png)
Looks a bit better in prod cortex, but still not right:
![screenshot_2017-03-19_08-37-50](https://cloud.githubusercontent.com/assets/109109/24079418/696482ea-0c7f-11e7-8b67-469a9712eb5f.png)

**Comment by Bplotka** [comment]
I think it would be useful to see the same RAW metrics in the same time range to compare if the samples are missing or wrong.

I think any network lag can cause this, since as discussed on slack channel - there is no Prometheus retry logic on 5xx. I have experienced similar thing -  might me related. Would be useful to actually see `nginx` metrix for served 504 on `api/prom/push` (there should be prom exporter somewhere opensourced).

**Comment by rade** [comment]
This looks fine now. I suspect some data went missing due to problems with the varbit switch over the w/e.
