### ISSUE TITLE
Switch to new-style rules format

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#622]
Prom 2 has a YAML syntax for defining alerting and recording rules. We should switch to that. I don't think we need backwards compatibility—we can probably get away with a one-off migration—but am open to differing opinions.

Mildly related to #619 (and thus #620).

CC @juliusv

**Comment by juliusv** [comment]
I'm on this now. It needs some prep refactoring work because this change needs a vendored Prometheus version that includes https://github.com/prometheus/prometheus/pull/3722, and that requires whole lot of other package compatibility changes in Cortex due to other unrelated updates in the Prometheus packages and their dependencies.
